<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCoxNHGv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCoxNHGv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCoxNHGv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCoxNHGv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCoxNHGv\App_KernelDevDebugContainer([
    'container.build_hash' => 'CoxNHGv',
    'container.build_id' => '6c06f103',
    'container.build_time' => 1615814614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCoxNHGv');
